import type { CslbTopicId } from "./topics";

export type CslbOption = {
  en: string;
  ru: string;
};

export type CslbQuestion = {
  id: string;
  topicId: CslbTopicId;
  textEn: string;
  textRu: string;
  options: [CslbOption, CslbOption, CslbOption, CslbOption];
  correctIndex: 0 | 1 | 2 | 3;
  explainEn: string;
  explainRu: string;
};

export const CSLB_QUESTIONS: CslbQuestion[] = [
  {
    id: "q-lic-01",
    topicId: "licensing",
    textEn: "A California contractor license is generally required when the price of labor and materials is:",
    textRu: "Лицензия подрядчика в Калифорнии обычно нужна, когда цена труда и материалов:",
    options: [
      { en: "$500 or more", ru: "500 долларов или больше" },
      { en: "$1,000 or more", ru: "1 000 долларов или больше" },
      { en: "$5,000 or more", ru: "5 000 долларов или больше" },
      { en: "Any amount, even a $50 service call", ru: "Любая сумма, даже выезд за 50 долларов" },
    ],
    correctIndex: 1,
    explainEn: "The minor-work exemption is under $1,000 for labor plus materials. At $1,000 or more you need a CSLB license.",
    explainRu: "Порог «мелкой работы» — меньше 1 000 долларов (труд плюс материалы). От 1 000 нужна лицензия CSLB.",
  },
  {
    id: "q-lic-02",
    topicId: "licensing",
    textEn: "For a C-61 / D-28 (doors, gates, and activating devices) license, the qualifier must pass:",
    textRu: "Для лицензии C-61 / D-28 (двери, ворота и автоматика) qualifier должен сдать:",
    options: [
      { en: "The Law and Business exam only — no trade exam", ru: "Только Law and Business, без trade-экзамена" },
      { en: "A garage-door trade exam and Law and Business", ru: "Trade-экзамен по воротам и Law and Business" },
      { en: "A C-10 electrical exam", ru: "Экзамен C-10 (электрика)" },
      { en: "No exam of any kind", ru: "Никакого экзамена" },
    ],
    correctIndex: 0,
    explainEn: "C-61 Limited Specialty classifications have no trade exam. The qualifier still takes CSLB Law and Business.",
    explainRu: "У C-61 Limited Specialty нет trade-экзамена. Qualifier всё равно сдаёт Law and Business.",
  },
  {
    id: "q-lic-03",
    topicId: "licensing",
    textEn: "The qualifier on a contractor license must:",
    textRu: "Qualifier на лицензии подрядчика обязан:",
    options: [
      { en: "Lend the license to any crew that needs it that week", ru: "Давать лицензию любой бригаде на неделю" },
      { en: "Exercise direct supervision and control of the construction operations", ru: "Реально руководить и контролировать работы" },
      { en: "Only sign checks; field work can be unsupervised", ru: "Только подписывать чеки; в поле можно без надзора" },
      { en: "Live in another state as long as the bond is paid", ru: "Жить в другом штате, если бонд оплачен" },
    ],
    correctIndex: 1,
    explainEn: "The RME/RMO is personally responsible. CSLB expects real supervision and control, not a rented license.",
    explainRu: "RME/RMO лично отвечает. CSLB требует реальное руководство, а не «аренду лицензии».",
  },
  {
    id: "q-lic-04",
    topicId: "licensing",
    textEn: "A contractor who does license-required work without a license generally:",
    textRu: "Подрядчик, который делает лицензируемую работу без лицензии, обычно:",
    options: [
      { en: "May still sue the owner in court to collect the full contract price", ru: "Может подать в суд и взыскать всю сумму договора" },
      { en: "Cannot use the courts to collect compensation for that work", ru: "Не может через суд взыскать оплату за эту работу" },
      { en: "Is automatically covered if the homeowner was happy", ru: "Автоматически в порядке, если заказчик доволен" },
      { en: "Only needs a city business tax certificate", ru: "Достаточно городского business tax certificate" },
    ],
    correctIndex: 1,
    explainEn: "Business and Professions Code 7031 bars an unlicensed contractor from recovering compensation in court for work that required a license.",
    explainRu: "B&P 7031: без лицензии нельзя взыскать оплату в суде за работу, для которой лицензия была нужна.",
  },
  {
    id: "q-con-01",
    topicId: "contracts",
    textEn: "A home improvement contract in California must generally be in writing when the contract price is:",
    textRu: "Home improvement contract в Калифорнии обычно должен быть письменным, если цена:",
    options: [
      { en: "More than $500", ru: "Больше 500 долларов" },
      { en: "More than $1,000", ru: "Больше 1 000 долларов" },
      { en: "More than $10,000", ru: "Больше 10 000 долларов" },
      { en: "Only when the customer asks for a written contract", ru: "Только если заказчик сам просит письменный договор" },
    ],
    correctIndex: 0,
    explainEn: "Civil Code 7159 home improvement contracts must be in writing when the price is more than $500 — a different number from the $1,000 license threshold.",
    explainRu: "По Civil Code 7159 письменный HIC нужен при цене больше 500 долларов. Это не тот же порог, что 1 000 на лицензию.",
  },
  {
    id: "q-con-02",
    topicId: "contracts",
    textEn: "The maximum down payment on a California home improvement contract is:",
    textRu: "Максимальный аванс по калифорнийскому home improvement contract:",
    options: [
      { en: "50% of the contract price", ru: "50% цены договора" },
      { en: "The full price if the parts are ordered that day", ru: "Вся сумма, если детали заказывают в тот же день" },
      { en: "$1,000 or 10% of the contract price, whichever is less", ru: "1 000 долларов или 10% цены — что меньше" },
      { en: "$2,500 regardless of the job size", ru: "2 500 долларов независимо от размера заказа" },
    ],
    correctIndex: 2,
    explainEn: "Down payment is capped at $1,000 or 10% of the contract price, whichever is less.",
    explainRu: "Аванс ограничен: 1 000 долларов или 10% цены договора — что меньше.",
  },
  {
    id: "q-con-03",
    topicId: "contracts",
    textEn: "A homeowner generally may cancel a home improvement contract until midnight of the:",
    textRu: "Заказчик обычно может отказаться от home improvement contract до полуночи:",
    options: [
      { en: "Same day the contract is signed", ru: "Того же дня, когда подписали договор" },
      { en: "Third business day after signing (fifth if the buyer is 65 or older)", ru: "Третьего рабочего дня после подписи (пятого, если покупателю 65+)" },
      { en: "Thirtieth calendar day after installation", ru: "Тридцатого календарного дня после установки" },
      { en: "Homeowner has no cancellation right once work is scheduled", ru: "Права отказа нет, как только работу поставили в график" },
    ],
    correctIndex: 1,
    explainEn: "The cooling-off period is three business days, or five business days when the buyer is 65 or older. Notice of Cancellation must be given.",
    explainRu: "Отказ — 3 рабочих дня, или 5, если покупателю 65+. Нужен Notice of Cancellation.",
  },
  {
    id: "q-con-04",
    topicId: "contracts",
    textEn: "Which item must appear on a home improvement contract?",
    textRu: "Что обязательно должно быть в home improvement contract?",
    options: [
      { en: "The salesperson's personal cell phone only", ru: "Только личный мобильный продавца" },
      { en: "The contractor's CSLB license number", ru: "Номер лицензии CSLB подрядчика" },
      { en: "A statement that verbal extra work is automatically approved", ru: "Фраза, что устные допы одобрены автоматически" },
      { en: "The contractor's tax return from last year", ru: "Налоговая декларация подрядчика за прошлый год" },
    ],
    correctIndex: 1,
    explainEn: "The license number must be on the contract (and in ads). Extra work still needs a written change order.",
    explainRu: "Номер лицензии обязан быть в договоре (и в рекламе). Допы всё равно оформляют письменным change order.",
  },
  {
    id: "q-fin-01",
    topicId: "finance",
    textEn: "If the owner asks for extra work after the contract is signed, the contractor should:",
    textRu: "Если после подписи договора заказчик просит дополнительную работу, подрядчик должен:",
    options: [
      { en: "Do the extra work first and agree on a price later", ru: "Сначала сделать, цену согласовать потом" },
      { en: "Get a written change order signed before starting that extra work", ru: "Получить подписанный письменный change order до начала этой работы" },
      { en: "Add 20% to the next invoice without telling the owner", ru: "Накинуть 20% на следующий инвойс молча" },
      { en: "Refuse all extras — change orders are illegal", ru: "Отказать во всех допах — change order незаконен" },
    ],
    correctIndex: 1,
    explainEn: "Extras need a written change order with the price and scope, signed before that work starts.",
    explainRu: "Допы — письменный change order с ценой и объёмом, подпись до начала этой работы.",
  },
  {
    id: "q-fin-02",
    topicId: "finance",
    textEn: "A progress payment on a home improvement job may not:",
    textRu: "Промежуточный платёж по home improvement не может:",
    options: [
      { en: "Be listed in the contract at all", ru: "Вообще указываться в договоре" },
      { en: "Exceed the value of work actually performed", ru: "Превышать стоимость уже выполненной работы" },
      { en: "Be collected after the work is finished", ru: "Браться после окончания работы" },
      { en: "Be paid by check", ru: "Оплачиваться чеком" },
    ],
    correctIndex: 1,
    explainEn: "You cannot take progress payments larger than the work completed (plus materials delivered, as the contract allows).",
    explainRu: "Нельзя брать progress payment больше, чем стоит уже сделанная работа (плюс материалы, если так в договоре).",
  },
  {
    id: "q-fin-03",
    topicId: "finance",
    textEn: "Starting a job and then walking away without a lawful reason is called:",
    textRu: "Начать работу и уйти без законной причины называется:",
    options: [
      { en: "A change order", ru: "Change order" },
      { en: "A mechanics lien", ru: "Mechanics lien" },
      { en: "Abandonment", ru: "Abandonment (бросить объект)" },
      { en: "A preliminary notice", ru: "Preliminary notice" },
    ],
    correctIndex: 2,
    explainEn: "Abandonment is a cause for discipline. You must complete the contracted work or have a lawful reason to stop.",
    explainRu: "Abandonment — основание для дисциплинарки CSLB. Нужно закончить работу по договору или иметь законную причину остановиться.",
  },
  {
    id: "q-fin-04",
    topicId: "finance",
    textEn: "A written estimate that the owner never signed is:",
    textRu: "Письменная смета, которую заказчик не подписал, — это:",
    options: [
      { en: "Automatically a binding home improvement contract", ru: "Автоматически обязательный home improvement contract" },
      { en: "Not a contract until both sides agree in the required written form", ru: "Не договор, пока обе стороны не согласятся в нужной письменной форме" },
      { en: "Enough to collect a 50% down payment", ru: "Достаточно, чтобы взять 50% аванса" },
      { en: "A mechanics lien on the property", ru: "Mechanics lien на дом" },
    ],
    correctIndex: 1,
    explainEn: "An estimate is an offer. It becomes a contract only when accepted in the form the law requires (for HIC, a proper written contract).",
    explainRu: "Смета — это предложение. Договором она становится только когда принята в форме, которую требует закон (для HIC — правильный письменный контракт).",
  },
  {
    id: "q-emp-01",
    topicId: "employment",
    textEn: "Workers' compensation insurance is required when the contractor:",
    textRu: "Workers' compensation обязательна, когда у подрядчика:",
    options: [
      { en: "Has even one employee", ru: "Есть хотя бы один employee" },
      { en: "Grosses more than $100,000 a year", ru: "Оборот больше 100 000 долларов в год" },
      { en: "Works only on residential garage doors", ru: "Работает только по жилым гаражным воротам" },
      { en: "Already has a contractor's bond", ru: "Уже есть contractor's bond" },
    ],
    correctIndex: 0,
    explainEn: "Any employee triggers workers' comp. A contractor's bond is not a substitute.",
    explainRu: "Любой employee включает обязанность workers' comp. Bond её не заменяет.",
  },
  {
    id: "q-emp-02",
    topicId: "employment",
    textEn: "Paying a helper in cash and calling the person an independent contractor, while you set the hours and methods, is:",
    textRu: "Платить помощнику наличными и называть его independent contractor, хотя вы задаёте часы и способ работы, — это:",
    options: [
      { en: "Always legal if they use their own screwdriver", ru: "Всегда законно, если у него своя отвёртка" },
      { en: "A misclassification risk — they may still be an employee", ru: "Риск ошибочной классификации: это всё ещё может быть employee" },
      { en: "Required by CSLB for C-61 licenses", ru: "Так требует CSLB для C-61" },
      { en: "Allowed if they sign a one-line receipt", ru: "Можно, если подпишут однострочную расписку" },
    ],
    correctIndex: 1,
    explainEn: "California (including AB 5) looks at control and the nature of the work. A label on a receipt does not make someone a true independent contractor.",
    explainRu: "Калифорния (включая AB 5) смотрит на контроль и суть работы. Надпись на расписке не делает человека настоящим independent contractor.",
  },
  {
    id: "q-emp-03",
    topicId: "employment",
    textEn: "California payroll taxes for employees are handled through:",
    textRu: "Налоги с зарплаты employees в Калифорнии идут через:",
    options: [
      { en: "CSLB only", ru: "Только CSLB" },
      { en: "The Employment Development Department (EDD)", ru: "Employment Development Department (EDD)" },
      { en: "Cal/OSHA", ru: "Cal/OSHA" },
      { en: "The city building department", ru: "Городской building department" },
    ],
    correctIndex: 1,
    explainEn: "EDD handles state payroll taxes and unemployment. CSLB licenses contractors; it is not the payroll tax agency.",
    explainRu: "EDD — штатные payroll taxes и unemployment. CSLB лицензирует подрядчиков, это не налоговая по зарплате.",
  },
  {
    id: "q-emp-04",
    topicId: "employment",
    textEn: "A workers' compensation exemption is generally available only if:",
    textRu: "Exemption от workers' compensation обычно доступен только если:",
    options: [
      { en: "The company has no employees", ru: "В компании нет employees" },
      { en: "All employees agree to waive coverage in writing", ru: "Все сотрудники письменно отказались от страховки" },
      { en: "The contractor carries a $25,000 bond", ru: "У подрядчика бонд на 25 000 долларов" },
      { en: "Jobs are under $1,000", ru: "Заказы дешевле 1 000 долларов" },
    ],
    correctIndex: 0,
    explainEn: "You may file an exemption when there are no employees. Employees cannot waive workers' comp to save the boss money.",
    explainRu: "Exemption подают, когда employees нет. Сотрудники не могут «отказаться» от workers' comp, чтобы сэкономить хозяину.",
  },
  {
    id: "q-bon-01",
    topicId: "bonds",
    textEn: "A contractor's license bond is primarily meant to:",
    textRu: "Contractor's license bond в первую очередь нужен, чтобы:",
    options: [
      { en: "Pay for damage to the contractor's truck", ru: "Оплатить ущерб грузовику подрядчика" },
      { en: "Protect consumers from certain license-law violations", ru: "Защитить заказчиков от ряда нарушений лицензионного закона" },
      { en: "Replace workers' compensation", ru: "Заменить workers' compensation" },
      { en: "Guarantee the contractor a bank loan", ru: "Гарантировать подрядчику банковский кредит" },
    ],
    correctIndex: 1,
    explainEn: "The bond is a consumer-protection requirement for the license. It is not auto insurance and not workers' comp.",
    explainRu: "Бонд — защита потребителя как условие лицензии. Это не автостраховка и не workers' comp.",
  },
  {
    id: "q-bon-02",
    topicId: "bonds",
    textEn: "To protect mechanics lien rights, a subcontractor or supplier generally must serve a preliminary notice within:",
    textRu: "Чтобы сохранить право на mechanics lien, sub или поставщик обычно должен подать preliminary notice в течение:",
    options: [
      { en: "20 days of first furnishing labor or materials", ru: "20 дней с первой поставки труда или материалов" },
      { en: "90 days after the job is advertised", ru: "90 дней после рекламы заказа" },
      { en: "One year after final payment", ru: "Года после финальной оплаты" },
      { en: "24 hours of signing the subcontract", ru: "24 часов после подписи субподряда" },
    ],
    correctIndex: 0,
    explainEn: "The 20-day preliminary notice is the classic timing rule. Missing it can cost lien rights.",
    explainRu: "Классический срок — 20-day preliminary notice. Пропуск может стоить права на lien.",
  },
  {
    id: "q-bon-03",
    topicId: "bonds",
    textEn: "A mechanics lien on a construction job is:",
    textRu: "Mechanics lien — это:",
    options: [
      { en: "A criminal fine paid to CSLB", ru: "Уголовный штраф в CSLB" },
      { en: "A claim against the property for unpaid labor or materials", ru: "Требование к недвижимости за неоплаченный труд или материалы" },
      { en: "The same thing as a contractor's bond", ru: "То же самое, что contractor's bond" },
      { en: "A Cal/OSHA citation", ru: "Предписание Cal/OSHA" },
    ],
    correctIndex: 1,
    explainEn: "A mechanics lien is recorded against the property so unpaid construction debt can be collected from the real estate.",
    explainRu: "Mechanics lien регистрируют на объект, чтобы долг за стройку можно было взыскать через недвижимость.",
  },
  {
    id: "q-bon-04",
    topicId: "bonds",
    textEn: "Most California contractor licenses require a contractor's bond in the amount of:",
    textRu: "Для большинства калифорнийских лицензий подрядчика нужен бонд на сумму:",
    options: [
      { en: "$5,000", ru: "5 000 долларов" },
      { en: "$15,000", ru: "15 000 долларов" },
      { en: "$25,000", ru: "25 000 долларов" },
      { en: "$100,000", ru: "100 000 долларов" },
    ],
    correctIndex: 2,
    explainEn: "The standard contractor bond amount is $25,000 (it was raised from $15,000). Exam questions still try the old number as a trap.",
    explainRu: "Стандартный бонд — 25 000 долларов (раньше было 15 000). Старую сумму на экзамене дают как ловушку.",
  },
  {
    id: "q-saf-01",
    topicId: "safety",
    textEn: "Every California employer must have an IIPP. That means:",
    textRu: "У каждого калифорнийского работодателя должна быть IIPP. Это:",
    options: [
      { en: "A loan application at the contractor's bank", ru: "Заявка на кредит в банке подрядчика" },
      { en: "An Injury and Illness Prevention Program", ru: "Программа предотвращения травм и заболеваний" },
      { en: "An invoice payment plan", ru: "План рассрочки по инвойсам" },
      { en: "A CSLB advertising permit", ru: "Разрешение CSLB на рекламу" },
    ],
    correctIndex: 1,
    explainEn: "IIPP is the Cal/OSHA Injury and Illness Prevention Program. It is a safety requirement, not a finance form.",
    explainRu: "IIPP — программа Cal/OSHA по предотвращению травм. Это охрана труда, не финансовая форма.",
  },
  {
    id: "q-saf-02",
    topicId: "safety",
    textEn: "A serious injury or death on the job must be reported to Cal/OSHA within:",
    textRu: "О тяжёлой травме или смерти на работе нужно сообщить в Cal/OSHA в течение:",
    options: [
      { en: "8 hours", ru: "8 часов" },
      { en: "8 days", ru: "8 дней" },
      { en: "30 days", ru: "30 дней" },
      { en: "The next license renewal", ru: "До следующего продления лицензии" },
    ],
    correctIndex: 0,
    explainEn: "Serious injury, illness, or death must be reported to Cal/OSHA immediately — no later than 8 hours.",
    explainRu: "О serious injury, болезни или смерти сообщают в Cal/OSHA сразу — не позже 8 часов.",
  },
  {
    id: "q-saf-03",
    topicId: "safety",
    textEn: "Safety Data Sheets (SDS) must be:",
    textRu: "Safety Data Sheets (SDS) должны быть:",
    options: [
      { en: "Available to employees who work with the hazardous products", ru: "Доступны сотрудникам, которые работают с опасными веществами" },
      { en: "Filed only with CSLB and never shown to the crew", ru: "Сданы только в CSLB и не показываться бригаде" },
      { en: "Posted on the company Instagram", ru: "Выложены в Instagram компании" },
      { en: "Destroyed after the first use of the product", ru: "Уничтожены после первого использования продукта" },
    ],
    correctIndex: 0,
    explainEn: "Hazard communication: workers need access to SDS for chemicals they use (oils, solvents, cleaners, etc.).",
    explainRu: "Hazard communication: у работников должен быть доступ к SDS на химикаты, с которыми они работают.",
  },
  {
    id: "q-saf-04",
    topicId: "safety",
    textEn: "Who is responsible for providing a safe workplace and required safety training?",
    textRu: "Кто отвечает за безопасное рабочее место и нужное обучение по safety?",
    options: [
      { en: "Each employee, personally, with no duty on the employer", ru: "Каждый сотрудник лично, у работодателя обязанности нет" },
      { en: "The employer", ru: "Работодатель" },
      { en: "The homeowner on every residential job", ru: "Хозяин дома на каждом жилом заказе" },
      { en: "CSLB inspectors only", ru: "Только инспекторы CSLB" },
    ],
    correctIndex: 1,
    explainEn: "Cal/OSHA puts the duty on the employer. An employee mistake does not erase that duty.",
    explainRu: "Cal/OSHA вешает обязанность на работодателя. Ошибка сотрудника эту обязанность не снимает.",
  },
  {
    id: "q-pub-01",
    topicId: "public-works",
    textEn: "Prevailing wage generally must be paid on:",
    textRu: "Prevailing wage обычно нужно платить на:",
    options: [
      { en: "Every private garage-door repair", ru: "Любом частном ремонте гаражных ворот" },
      { en: "Public works projects paid with public funds", ru: "Public works, которые оплачивают публичные деньги" },
      { en: "Jobs under $500 only", ru: "Только на заказах дешевле 500 долларов" },
      { en: "Cash jobs so they stay off the books", ru: "Наличных заказах, чтобы не светить в учёте" },
    ],
    correctIndex: 1,
    explainEn: "Prevailing wage is a public-works rule, not a private residential service-call rule.",
    explainRu: "Prevailing wage — правило public works, не частного выезда к жильцу.",
  },
  {
    id: "q-pub-02",
    topicId: "public-works",
    textEn: "Contractors who bid most California public works jobs must be registered with:",
    textRu: "Подрядчики, которые идут на большинство калифорнийских public works, должны быть зарегистрированы в:",
    options: [
      { en: "The Department of Industrial Relations (DIR)", ru: "Department of Industrial Relations (DIR)" },
      { en: "The Department of Motor Vehicles (DMV)", ru: "DMV" },
      { en: "The post office", ru: "Почте" },
      { en: "Yelp", ru: "Yelp" },
    ],
    correctIndex: 0,
    explainEn: "DIR public-works contractor registration is the usual requirement before bidding those jobs.",
    explainRu: "Обычно нужна регистрация подрядчика DIR, прежде чем идти на такие тендеры.",
  },
  {
    id: "q-pub-03",
    topicId: "public-works",
    textEn: "Certified payroll records on a public works job are used to:",
    textRu: "Certified payroll на public works нужен, чтобы:",
    options: [
      { en: "Show the homeowner a marketing brochure", ru: "Показать заказчику рекламную брошюру" },
      { en: "Document that workers were paid the required prevailing wages", ru: "Подтвердить, что людям заплатили положенный prevailing wage" },
      { en: "Replace the contractor's license bond", ru: "Заменить contractor's bond" },
      { en: "Cancel the 3-day notice of cancellation", ru: "Отменить 3-дневный Notice of Cancellation" },
    ],
    correctIndex: 1,
    explainEn: "Certified payroll is the paper trail that prevailing wage was actually paid.",
    explainRu: "Certified payroll — бумажный след, что prevailing wage реально выплатили.",
  },
  {
    id: "q-pub-04",
    topicId: "public-works",
    textEn: "Replacing a garage door at a privately owned house paid by the homeowner is:",
    textRu: "Замена гаражных ворот в частном доме за счёт хозяина — это:",
    options: [
      { en: "Always a public works project", ru: "Всегда public works" },
      { en: "Generally not public works", ru: "Обычно не public works" },
      { en: "Public works if the house is in California", ru: "Public works, если дом в Калифорнии" },
      { en: "Public works if the invoice is over $1,000", ru: "Public works, если инвойс больше 1 000 долларов" },
    ],
    correctIndex: 1,
    explainEn: "A private homeowner paying for their own door is not public works. Public funds (city, school, state) are the usual trigger.",
    explainRu: "Частный хозяин платит за свои ворота — это не public works. Обычно триггер — публичные деньги (город, школа, штат).",
  },
];

export function questionsForTopic(topicId: CslbTopicId): CslbQuestion[] {
  return CSLB_QUESTIONS.filter((q) => q.topicId === topicId);
}

export function getCslbQuestion(id: string): CslbQuestion | undefined {
  return CSLB_QUESTIONS.find((q) => q.id === id);
}
