/** Champion on-hand from the physical count. Pair rows already split into red + black. */

export type ChampionPaperCount = {
  name: string;
  qty: number;
};

export const CHAMPION_PAPER_COUNTS: ChampionPaperCount[] = [
  { name: "LM 2420L 7-ft", qty: 1 },
  { name: "LM 6690L-267 7-ft", qty: 1 },
  { name: "LM 98022 (Jackshaft)", qty: 0 },
  { name: "Chamberlain B3010", qty: 0 },
  { name: "LM 8-ft belt rail", qty: 1 },
  { name: "LM 7-ft belt rail", qty: 1 },
  { name: "Chamberlain 7' belt rail", qty: 0 },
  { name: "LM 7-ft chain rail", qty: 1 },

  { name: "207*27 (red)", qty: 2 },
  { name: "207*27 (black)", qty: 1 },
  { name: "218*28 (red)", qty: 1 },
  { name: "218*28 (black)", qty: 2 },
  { name: "225*28 (red)", qty: 3 },
  { name: "225*28 (black)", qty: 2 },
  { name: "234*30 (red)", qty: 2 },
  { name: "234*30 (black)", qty: 3 },
  { name: "243*33 (red)", qty: 1 },
  { name: "243*33 (black)", qty: 2 },
  { name: "250*33 (red)", qty: 2 },
  { name: "250*33 (black)", qty: 2 },
  { name: "262*34 (red)", qty: 1 },
  { name: "262*34 (black)", qty: 1 },
  { name: "728 (single)", qty: 4 },
  { name: "928 (single)", qty: 2 },
  { name: "730 (single)", qty: 0 },
  { name: "W Hook", qty: 4 },

  { name: 'Rollers 4"', qty: 20 },
  { name: 'Rollers Z Bearing 4"', qty: 20 },
  { name: 'Rollers 7"', qty: 20 },
  { name: 'Bottom seal (blk 4")', qty: 0 },
  { name: 'Bottom seal (gray 4")', qty: 1 },
  { name: 'Bottom seal (gray 6")', qty: 1 },
  { name: "Bottom seal wood door 16ft", qty: 1 },
  { name: "Bottom retainer (T shape 16-ft)", qty: 0 },
  { name: "Bottom retainer 1-3/8 (L shape 16-ft)", qty: 0 },
  { name: "Bottom retainer 1-7/8 (L shape 16-ft)", qty: 1 },
  { name: "Emergency release lock", qty: 3 },
  { name: "T-lock", qty: 1 },
  { name: "T-lock handle", qty: 0 },
  { name: "Slide lock", qty: 1 },
  { name: "Cable 7-ft", qty: 1 },
  { name: "Cable 8-ft", qty: 2 },
  { name: "End plates", qty: 2 },
  { name: "End plates (low headroom)", qty: 1 },
  { name: "Center bearing", qty: 2 },
  { name: "Nylon center bearing", qty: 2 },
  { name: "Drums 8ft", qty: 1 },
  { name: "Drums 12ft", qty: 1 },
  { name: "Strut 16-ft", qty: 3 },
  { name: "Strut 8-ft", qty: 0 },
  { name: "Torsion tube 16-ft", qty: 0 },
  { name: "Torsion tube 16-ft (11g)", qty: 0 },
  { name: "Vertical tracks 7-ft", qty: 1 },

  { name: "889 LM wall console", qty: 1 },
  { name: "LM 7-ft Belt (041a3589-3) old style", qty: 2 },
  { name: "LM 8-ft Belt (041a3589-1) old style", qty: 1 },
  { name: "LM 7-ft Belt (041a5434-11A) new style", qty: 1 },
  { name: "LM 8-ft Belt (041a5434-13A) new style", qty: 1 },
  { name: "LM photo eye", qty: 2 },
  { name: "LM gear sprocket chain (041C4220A)", qty: 1 },
  { name: "LM gear sprocket belt (041A4885-5)", qty: 0 },
  { name: "LM coupler", qty: 3 },
  { name: "LM screw drive rack", qty: 0 },
  { name: "LM 380UT remote", qty: 5 },
  { name: "LM 891 remote", qty: 0 },
  { name: "LM 893 remote", qty: 0 },
  { name: "LM 878 MAX keypad", qty: 2 },
  { name: "LM L979M keypad", qty: 3 },
  { name: "LM L992U remote", qty: 1 },
  { name: "CH361 remote", qty: 0 },
  { name: "850 LM receiver", qty: 1 },
  { name: "85 LM transformer", qty: 1 },
  { name: "365 LM receiver", qty: 0 },

  { name: "GN capacitor 1/2hp (19988A)", qty: 2 },
  { name: "GN photo eye", qty: 2 },
  { name: "GN trolley (screw drive)", qty: 3 },
  { name: "GN coupler", qty: 0 },
  { name: "GK-BX keypad", qty: 1 },
  { name: "Mtec photo eye", qty: 1 },
  { name: "Mtec remotes", qty: 2 },
  { name: "Hinge #1", qty: 3 },
  { name: "Hinge #2", qty: 2 },
  { name: "Hinge #3", qty: 4 },
  { name: "Hinge #4", qty: 4 },
  { name: "Hinge #5", qty: 2 },
  { name: "Bottom brackets", qty: 2 },
  { name: "Top brackets (single)", qty: 2 },
  { name: "Top brackets low head (single)", qty: 2 },
  { name: "Spring center bracket", qty: 1 },
  { name: "Jamb brackets #8", qty: 4 },
  { name: "Orb bracket", qty: 1 },
];
